refactor: update passport branding
nation3/mobile-passport pull request #32
Opened 2022-06-28 10:01 UTC by aahna-ashina

#4

- Replace `strip.png`
- Move Issue Date from `secondaryFields` to `headerFields`
- Rename from "Holder" to "Citizen Name"
- Rename from "Passport ID" to "Number"

<img width="690" alt="Screen Shot 2022-06-28 at 5 53 59 PM" src="https://user-images.githubusercontent.com/95955389/176150680-376ad606-4e09-45d5-b364-a60dbefbfb58.png">

# iOS

![Screen Shot 2022-06-28 at 5 49 31 PM](https://user-images.githubusercontent.com/95955389/176150744-b3019bf0-1347-4aac-a731-9320d31982ae.png)

# Android

## WalletPasses

<img src="https://user-images.githubusercontent.com/95955389/176152024-bd61211e-4bda-4732-9cbf-95180c869b74.jpeg" width="320" />

## PassWallet

<img src="https://user-images.githubusercontent.com/95955389/176152007-96c889f0-6bcc-4f92-aca7-caa946fa9f4b.jpeg" width="320" />

2022-06-28 10:50 UTC, xPi2 commented
![28eb74fb-d4fe-47fc-b732-95251a14ee2f](https://user-images.githubusercontent.com/32301192/176161294-f853119f-b032-46e6-be55-43fe607c05f1.jpg)
This is how it looks on an iPhone 11. I think we have make some tweaks to de layout.

2022-06-28 10:54 UTC, xPi2 commented
@aahna-ashina Did you try to use something like this example for the date formatting?
```
            {
                "dateStyle" : "PKDateStyleMedium",
                "isRelative" : true,
                "key" : "doors-open",
                "label" : "Doors open",
                "timeStyle" : "PKDateStyleShort",
                "value" : "2013-08-10T19:30-06:00"
            }
 ```
 From "Fields Support Formatting" on [Pass design and creation](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1)

2022-06-28 10:58 UTC, xPi2 commented
Finally, do you think we can fill the backFields with the passport information?
Something like:
- Issue Date
- Number
- Passport Holder
- Issuer (Nation3)

2022-06-28 11:00 UTC, xPi2 commented on server/template-versions/apple/1/pass.json
> +        "label": "Citizen Name",
```suggestion
        "label": "Passport Holder",
```
This was my fault, the design on figma was outdated, on the passport token we are using this label.

2022-06-28 13:37 UTC, luisivan commented
Seeing how the date looks on the top right corner (quite compressed) maybe we should move it as a normal field below the passport holder field. Thoughts @aahna-ashina?

2022-06-29 05:11 UTC, aahna-ashina commented
> Seeing how the date looks on the top right corner (quite compressed) maybe we should move it as a normal field below the passport holder field. Thoughts @aahna-ashina?

@luisivan Yes, I think that looks better.  It would also solve the problem of the header fields being displayed in a different order on certain iOS versions and certain Android apps.

Fixed here: https://github.com/nation3/mobile-passport/pull/32/commits/a4f4ce7743b3778a120a4343214af78cdc85b001

![Screen Shot 2022-06-29 at 1 07 54 PM](https://user-images.githubusercontent.com/95955389/176356550-1268863c-01fc-4392-b128-1719fd5ecea0.png)

2022-06-29 05:17 UTC, aahna-ashina commented
> Did you try to use something like this example for the date formatting?

@xPi2 Yes, we can change the issue date formatting to "08/06/22" as presented in the [mockup](https://github.com/nation3/brand/blob/main/passport/pass/mockup.png), but wouldn't that cause confusion?  How will you know what is the day, month and year?  Maybe you had another date formatting than "08/06/22" in mind?

2022-06-29 05:45 UTC, aahna-ashina commented
> Finally, do you think we can fill the backFields with the passport information?

@xPi2 Done:  https://github.com/nation3/mobile-passport/pull/32/commits/d28974fd298862f6ac2f5b370e4b58e1ef72a203

2022-06-29 07:58 UTC, xPi2 approved these changes
I've tested the new version on iOS. Looks great!

2022-06-29 08:54 UTC, luisivan requested changes
Just one more thing I realized: What was the rationale to rename from "Holder" to "Citizen Name"? Knowing that not everyone has an ENS name, "Holder" would be more appropriate.

2022-06-29 09:06 UTC, aahna-ashina commented
> Just one more thing I realized: What was the rationale to rename from "Holder" to "Citizen Name"? Knowing that not everyone has an ENS name, "Holder" would be more appropriate.

@luisivan It was because I saw it in the [mockup](https://github.com/nation3/brand/blob/main/passport/pass/mockup.png) design.  But reverted the change back to "Passport Holder" after @xPi2's code review: https://github.com/nation3/mobile-passport/pull/32/commits/ac3a21548d01ecdf40fb4c0091f15c9db228428d

![Screen Shot 2022-06-29 at 5 05 18 PM](https://user-images.githubusercontent.com/95955389/176398135-10f750d7-9671-408a-a78a-8857552dce33.png)

![Screen Shot 2022-06-29 at 5 05 30 PM](https://user-images.githubusercontent.com/95955389/176398189-c10ab58e-92f5-460e-87aa-f5f26e51d5d9.png)

2022-06-29 09:17 UTC, merged