feat(): Add Splitbee analytics for pass downloads
nation3/mobile-passport pull request #33
Opened 2022-06-29 15:42 UTC by luisivan

PS: On a different note, we should add Prettifier config files to all projects to avoid noise in PRs

2022-06-30 08:34 UTC, aahna-ashina requested changes
@luisivan This PR is both adding Splitbee _and_ doing a lot of refactoring at the same time, so it's not easy for code reviewers to read the Splitbee code diff.  Can you either 1) create one PR per change (one PR for refactoring, and another for Splitbee), or 2) create one PR with one commit per change (one commit for refactoring, and another for Splitbee)?  Thanks! 😃

(Here is a great pull request philosophy: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#pull-request-philosophy)

2022-06-30 09:46 UTC, luisivan commented
Yeah... that's what I was mentioning above, since we didn't have a Prettifier config, just doing a save on my editor refactored the whole thing 😄 

Maybe it's best to first merge https://github.com/nation3/mobile-passport/pull/34, and then this one after (and then the changes will only affect Splitbee)

2022-07-01 14:01 UTC, luisivan commented
@aahna-ashina ready to review again!

2022-07-01 14:51 UTC, aahna-ashina approved these changes
Looks good to me (though I have not tested the changes on `localhost` yet.

Out of curiosity:  Where will the collected analytics be made available? On the Splitbee website I'm assuming?

2022-07-01 14:51 UTC, aahna-ashina commented on server/pages/api/downloadPass.ts
> +const analytics = new SplitbeeAnalytics(process.env.SPLITBEE_TOKEN)
If the `SPLITBEE_TOKEN` is missing from `.env.local`, will the code still run on localhost?

2022-09-09 04:08 UTC, aahna-ashina commented
@luisivan This PR will be closed when we merge #73 because we can get the same pass details by querying the `downloads` table that was added:  https://github.com/nation3/mobile-passport/pull/73/commits/90afce23bd6dfbc4330c404505d8671b4719cc7e

```sql
select time_of_download, platform, address, passport_id from downloads;
```

2022-09-13 01:54 UTC, closed without merging