feat(apple): create an updatable pass (#53)
nation3/mobile-passport pull request #55
Opened 2022-08-20 02:02 UTC by aahna-ashina

## Dework Task

https://app.dework.xyz/nation3/app-2?taskId=063a5647-479d-47aa-ba6a-fbf3369acd8e

## GitHub Issue

close https://github.com/nation3/mobile-passport/issues/53

## How Has This Been Tested?

2022-08-23 09:18 UTC, luisivan commented
@aahna-ashina can you provide more info about how to obtain `APPLE_AUTH_TOKEN_HMAC_SEED ` and `APPLE_WEB_SERVICE_URL`? Thanks!

2022-08-24 11:23 UTC, aahna-ashina commented
> can you provide more info about how to obtain `APPLE_AUTH_TOKEN_HMAC_SEED ` and `APPLE_WEB_SERVICE_URL`? Thanks!

@luisivan Yes 😄

- The `APPLE_AUTH_TOKEN_HMAC_SEED ` variable can be any random string of characters, it just needs to be _different_ from the one used in [`.env.local.sample`](https://github.com/nation3/mobile-passport/pull/55/files#diff-75c9561a6558a85cc1b0645ec55fc66282778fb8e44cbc62e21da827f9a865e5R9)
  - Also note that once set, this variable should never be changed.

- The `APPLE_WEB_SERVICE_URL` must match the domain used for the Vercel deployment:
  - `APPLE_WEB_SERVICE_URL=https://passports.nation3.org/api/apple`

2022-08-25 16:15 UTC, luisivan commented
@aahna-ashina thanks, done!

2022-08-30 13:10 UTC, johnmark13 requested changes
Tiny change, always great work 💪

2022-08-30 13:10 UTC, johnmark13 commented on server/pages/api/pushUpdate.ts
> +  const templateFormatVersion: number = 2
I didn't think much of the 2 in downloadPass.ts, but assuming it relates to this 2 here, should probably be in config somewhere.

2022-08-30 13:13 UTC, aahna-ashina commented on server/pages/api/pushUpdate.ts
> +  const templateFormatVersion: number = 2
@johnmark13 Yes, absolutely agreed.  Will handle that when I get started on #6

2022-08-30 13:17 UTC, johnmark13 approved these changes

2022-08-30 15:10 UTC, luisivan approved these changes
Solid

2022-08-30 15:10 UTC, merged