test(api): add integration tests of api (#48)
nation3/mobile-passport pull request #56
Opened 2022-08-21 07:45 UTC by aahna-ashina

## Dework task

https://app.dework.xyz/nation3/develop-1?taskId=1458b989-c72d-4fb6-b9e9-ba931b4d7c24

## Related GitHub issue

#48

## How Has This Been Tested?

`npm run e2e:headless`

2022-08-21 18:45 UTC, gregfromstl requested changes

2022-08-21 18:45 UTC, gregfromstl commented on server/cypress/e2e/downloadPass.cy.ts
> +
We probably want one "Success" test to make sure it doesn't just throw a 400 error every time.

2022-08-23 10:34 UTC, aahna-ashina commented on server/cypress/e2e/downloadPass.cy.ts
> +
@gregfromstl Yes, absolutely, good point.  To test end-to-end the download of a generated `.pkpass` file, we will need to add support for Goerli to the passport API server, so I opened a PR for that here:  #59

2022-08-24 07:27 UTC, aahna-ashina commented on server/cypress/e2e/downloadPass.cy.ts
> +
@gregfromstl Once #59 has been merged, I will continue with this PR.

2022-08-26 08:21 UTC, johnmark13 approved these changes

2022-08-28 01:37 UTC, closed without merging