Refactor: Move middleware to root of server
nation3/mobile-passport pull request #64
Opened 2022-08-24 19:45 UTC by mikelee

This change moves nested middleware to the root which prevented upgrading to Next.js v12.2.5. Closes #62

2022-08-24 22:19 UTC, aahna-ashina commented
@xPi2 Could you authorize the Vercel deployment?

2022-08-24 23:36 UTC, aahna-ashina requested changes
@mikelee Basic Auth stopped working.

2022-08-25 21:49 UTC, mikelee commented
@aahna-ashina I updated next.js to 12.2.5 so the middleware will run. However, the sign in form doesn't pop up and the authorization header is null. I'm not sure what the problem is. Also, next.js doesn't allow a response to be returned from middleware in 12.2. They suggest redirecting to a login form or api route. I'm not what direction you want to go with it.

2022-08-26 03:56 UTC, mikelee commented
@aahna-ashina I got basic auth working by rewiting to an api route instead of returning a response.

2022-09-03 06:44 UTC, aahna-ashina commented
Thank you for the PR, @mikelee :-D

Looks like the integration tests expect "Unauthorized" to be present in the response body:  https://github.com/nation3/mobile-passport/runs/8167680193?check_suite_focus=true

Would it be possible to add this to `middleware.ts`?

2022-09-04 03:25 UTC, mikelee commented
> Thank you for the PR, @mikelee 😄
> 
> Looks like the integration tests expect "Unauthorized" to be present in the response body: https://github.com/nation3/mobile-passport/runs/8167680193?check_suite_focus=true
> 
> Would it be possible to add this to `middleware.ts`?

@aahna-ashina I added the "Unauthorized" response in unauthorized.ts since next.js doesn't allow responses from middleware in v12.2. All integration tests pass now.

2022-09-04 03:50 UTC, aahna-ashina approved these changes

2022-09-04 03:52 UTC, aahna-ashina commented
> I added the "Unauthorized" response in unauthorized.ts since next.js doesn't allow responses from middleware in v12.2. All integration tests pass now.

Thank you, @mikelee, looks great 😄

By the way, do you have a Dework username?  I got zero results when searching for https://app.dework.xyz/profile/mikelee

2022-09-05 21:12 UTC, mikelee commented
> Thank you, @mikelee, looks great 😄
> 
> By the way, do you have a Dework username? I got zero results when searching for https://app.dework.xyz/profile/mikelee

@aahna-ashina  Thanks. I didn't have an account, but I just made one.
https://app.dework.xyz/profile/mikelee

2022-09-06 00:28 UTC, aahna-ashina commented
> Thanks. I didn't have an account, but I just made one.
> https://app.dework.xyz/profile/mikelee

Thank you, @mikelee.  Can you also follow the Nation3 DAO at https://app.dework.xyz/nation3, please?  That way, we can add you to the Dework task.

2022-09-06 13:47 UTC, mikelee commented
> Thank you, @mikelee. Can you also follow the Nation3 DAO at https://app.dework.xyz/nation3, please? That way, we can add you to the Dework task.
@aahna-ashina Yup. Done.

2022-09-07 01:29 UTC, aahna-ashina commented
> Yup. Done.

@mikelee I don't think it worked.  After you click "Follow", Nation3 should show up on your profile.

2022-09-07 17:19 UTC, mikelee commented
> @mikelee I don't think it worked? After you click "Follow," Nation3 should show up on your profile: https://app.dework.xyz/profile/mikelee

That's weird. Nation3 is in my sidebar and I have the option to unfollow.

2022-09-08 09:30 UTC, johnmark13 approved these changes

2022-09-08 09:30 UTC, johnmark13 commented on server/middleware.ts
>        // Perform Basic Auth
This comment doesn't make any sense :D

2022-09-08 10:06 UTC, aahna-ashina commented on server/middleware.ts
>        // Perform Basic Auth
```suggestion
      // Redirect
```

2022-09-08 10:07 UTC, aahna-ashina commented on server/middleware.ts
>        // Perform Basic Auth
@johnmark13 I agree.  Changed it to "Redirect"

2022-09-08 10:10 UTC, merged