Apple Wallet: Unregister a Pass for Update Notifications (#68)
nation3/mobile-passport pull request #87
Opened 2022-09-30 07:37 UTC by aahna-ashina

![IMG_0140](https://user-images.githubusercontent.com/95955389/193216852-3c28c86f-5b1a-4eb3-8dd9-2a23673ea2c1.PNG) → ![IMG_B496F8735FB3-1](https://user-images.githubusercontent.com/95955389/193216859-b6794b39-0071-4aad-b717-4446429440a1.jpeg)

## Dework Task

https://app.dework.xyz/nation3/passport-services-p?taskId=5428fb8e-8c88-4186-ada6-6096bc4595ed

## Related GitHub Issue

closes #68

## How Has This Been Tested?

- [ ] Status checks pass
- [ ] Works on Goerli
- [ ] Works on Mainnet

## Are There Admin Tasks?

2022-09-30 11:51 UTC, johnmark13 requested changes
If my comment is unclear, I am happy to create some code to highlight what I mean!

2022-09-30 11:51 UTC, johnmark13 commented on server/pages/api/apple/v1/devices/[deviceLibraryIdentifier]/registrations/[passTypeIdentifier]/[serialNumber].ts
> +    }
Functionally this looks all good, I would use a `switch` rather than if/else and create a `handleAdd` and `handleDelete` method to simplify the code, the `default` can throw the `throw new Error('Wrong request method: ' + req.method)` from above meaning that code goes away, and if we add support for another method it just extends the case statement without having the logic in two places.

2022-09-30 11:54 UTC, aahna-ashina commented on server/pages/api/apple/v1/devices/[deviceLibraryIdentifier]/registrations/[passTypeIdentifier]/[serialNumber].ts
> +    }
@johnmark13 Yes, please.  Could you use the "Add a suggestion" feature in GitHub?  I think that would make it easier for me to understand.

> <img width="204" alt="Screen Shot 2022-09-30 at 7 53 25 PM" src="https://user-images.githubusercontent.com/95955389/193264048-8233f12d-d439-4402-a2c5-534ff9fad6c8.png">

2022-10-01 06:27 UTC, aahna-ashina commented on server/pages/api/apple/v1/devices/[deviceLibraryIdentifier]/registrations/[passTypeIdentifier]/[serialNumber].ts
> +    }
> create a `handleAdd` and `handleDelete` method to simplify the code

@johnmark13 Done:  https://github.com/nation3/mobile-passport/pull/87/commits/7c815e2d1b2dd3519da2787abfe24b33f338135e

2022-10-01 06:30 UTC, aahna-ashina commented on server/pages/api/apple/v1/devices/[deviceLibraryIdentifier]/registrations/[passTypeIdentifier]/[serialNumber].ts
> +    }
> if we add support for another method it just extends the case statement without having the logic in two places.

This endpoint will only support two methods, `[POST]` and `[DELETE]`:
- https://developer.apple.com/documentation/walletpasses/register_a_pass_for_update_notifications
- https://developer.apple.com/documentation/walletpasses/unregister_a_pass_for_update_notifications

2022-10-01 06:37 UTC, johnmark13 approved these changes
I have a lot if respect that you listen to me at all! I'd not pass the req/resp around to better separate concerns, but I think it is much neater this way, thanks

2022-10-01 07:38 UTC, aahna-ashina commented
> I'd not pass the req/resp around to better separate concerns

Fixed:  https://github.com/nation3/mobile-passport/pull/87/commits/c85214ac6a9a80b469d67b462dadf1db4775b236

2022-10-01 07:51 UTC, johnmark13 approved these changes

2022-10-03 08:28 UTC, johnmark13 commented on server/pages/api/apple/v1/devices/[deviceLibraryIdentifier]/registrations/[passTypeIdentifier]/[serialNumber].ts
> +    }
I think that would be cool, but 20 minutes of reading doesn't give me hope it can be done in NextJS. It is a fairly typical pattern in other frameworks to have almost no code in the API handler/controller/resolver injecting a service/CommandHandler into that class that does the work, decoupling the protocol from the business logic - for now I think that would be overkill.

2022-10-04 15:40 UTC, merged